[tox]
requires =
    tox>=4
env_list = unit, integration

[testenv]
skip_install = True
description = run unit tests
deps =
    pytest>=8
    numpy>=1.13.3,<2
    scipy<1.15.0
    mpi4py<4
commands =
    pipinstall --no-deps
    pytest {posargs:tests}
sitepackages = True


[testenv:unit]
commands =
    pytest tests/unit

[testenv:integration]
commands =
    pytest tests/integration

