[tox]
requires =
    tox>=4
env_list = all

[testenv]
skip_install = True
description = base environment for testing
deps =
    pytest>=8
    numpy>=1.13.3,<2
    scipy<1.15.0
    mpi4py>=3
sitepackages = True

[testenv:all]
description = run all tests
commands =
    pytest {posargs}

[testenv:unit]
description = run unit tests
commands =
    pytest tests/unit

[testenv:integration]
description = run integration tests
commands =
    pytest tests/integration
