[tox]
requires =
    tox>=4
env_list = unit, integration

[testenv]
description = run unit tests
deps =
    pytest>=8

commands =
    pytest {posargs:tests}
sitepackages = True


[testenv:unit]
commands =
    pytest tests/unit

[testenv:integration]
commands =
    pytest tests/integration

