name: Update docker image

on:
  workflow_dispatch: # Trigger by hand from the UI
    inputs:
      branch:
        type: choice
        description: branch to build the container from
        options:
          - develop
          - master     
  push:
    branches:
      - develop
      - master

jobs:
  build-and-release-docker-image:
    name: Builds a dockerimage with the fenics adapter of preCICE
    runs-on: ubuntu-latest
    env:
        docker_username: precice
    steps:
      - name: Set branch name for manual triggering
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        run: echo "branch=${{ inputs.branch }}" >> $GITHUB_ENV    
      - name: Set branch name for on pull triggering
        if: github.event_name != 'pull_request' && github.event_name != 'workflow_dispatch'
        shell: bash
        run: echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV    
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest Dockerfile
        uses: docker/build-push-action@v2
        if: ${{ env.branch }} == 'master'
        with:
          push: true
          file: "./tools/releasing/packaging/docker/Dockerfile"
          tags: ${{ env.docker_username }}/fenics-adapter:latest
          build-args: |
            branch=${{ env.branch }}
      - name: Build and push develop Dockerfile
        uses: docker/build-push-action@v2
        if: ${{ env.branch }} != 'master'
        with:
          push: true
          file: "./tools/releasing/packaging/docker/Dockerfile"
          tags: ${{ env.docker_username }}/fenics-adapter:${{ env.branch }}
          build-args: |
            branch=${{ env.branch }}
