name: Update docker image

on:
  workflow_dispatch:      # Trigger by hand from the UI
  push:
    branches:
      - develop
      - master

jobs:
  build-and-release-docker-image:
    name: Builds a dockerimage with the fenics adapter of preCICE
    runs-on: ubuntu-latest
    env:
        docker_username: precice
    steps:
      - name: Get branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV    
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest Dockerfile
        uses: docker/build-push-action@v2
        if: ${{ env.branch }} == 'master'
        with:
          push: true
          file: "./tools/releasing/packaging/docker/Dockerfile"
          tags: ${{ env.docker_username }}/fenics-adapter:latest
          build-args: |
            branch=${{ env.branch }}
      - name: Build and push develop Dockerfile
        uses: docker/build-push-action@v2
        if: ${{ env.branch }} != 'master'
        with:
          push: true
          file: "./tools/releasing/packaging/docker/Dockerfile"
          tags: ${{ env.docker_username }}/fenics-adapter:${{ env.branch }}
          build-args: |
            branch=${{ env.branch }}
